# coding: utf-8

class Vector2:
    '''
    Class representing a vector of 2 floats
    '''

    def __init__(self, x : float, y : float): ...
    x : float = ...
    y : float = ...


class Vector3:
    '''
    Class representing a vector of 3 floats
    '''

    def __init__(self, x : float, y : float, z : float): ...
    x : float = ...
    y : float = ...
    z : float = ...


class Vector4:
    '''
    Class representing a vector of 4 floats
    '''

    def __init__(self, x : float, y : float, z : float, w : float): ...
    x : float = ...
    y : float = ...
    z : float = ...
    w : float = ...