#pragma once

#ifdef TR_PLATFORM_WINDOWS

#define TR_SHADER_BUFFER_NOTATION "cbuffer"
#define TR_SHADER_STRUCT_NOTATION "struct"

#endif

#define TR_CLEAR_COLOR_R 1.0f
#define TR_CLEAR_COLOR_G 0.0f
#define TR_CLEAR_COLOR_B 1.0f
#define TR_CLEAR_COLOR_W 0.0f

#define TR_CLEAR_COLOR TR_CLEAR_COLOR_R, TR_CLEAR_COLOR_G, TR_CLEAR_COLOR_B, TR_CLEAR_COLOR_W

#define TR_MT_ENABLED 1